server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000


  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai
  data:
    redis:
      host: ${sky.redis.host}
      database: ${sky.redis.database}
      port: ${sky.redis.port}
      password: ${sky.redis.password}

  rabbitmq:
    host: ${sky.rabbitmq.host}
    port: ${sky.rabbitmq.port}
    username: ${sky.rabbitmq.username}
    password: ${sky.rabbitmq.password}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.sky.controller
  default-produces-media-type: application/json

knife4j:
  enable: true
  setting:
    language: zh_cn

sky:
  jwt:
    admin-secret-key: ENC(kwpPrIZuKyRKUULm/tC7FQxVAS9TUGinZ7RX7W9XK1PNGF5n/426SWfDN7YveOxP2y0ZpfKOiC0D1vjY36ncAHEobWwKBektLeJYKPVRIasf30TQ+oy0h16MjW963rLCwe/wl0VXGFBUwKZ48xALfw==)
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: ENC(KgF3DCI9Kdkuw/AP5rCw5bXO82yvYZHgx5TpwWHXEVxk5vPdDxHv1KZw4UUW6fAPYoRnU/iHjlPBvt6nueBtZxlsyYUsjB/1N1JPEOB/YipGdTAM3xjUdOD9OdDiziZiZDFoEwbePjgK1da+OCZNNA==)
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator