sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: mealflow
    username: root
    password: ENC(rYFJ/t8F/QQwCncg7IqzjdJigh2YI3bSG0Nn1Hmwuy0pCX3Si0mjyqkrqeT1PoPg)
  alioss:

    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ENC(MnO6Dhmaki/8eTROZu7S/BJuwLJaJHr8QDiJcea0Cz/EIT4l0JHM3oVhheb8DMRC41BJmjKgNxkFrMZyin1BUQ==)
    access-key-secret: ENC(Q7w/3ilRO4F/Q4Phqrf2+5MyRXygehUvA+I/LMKrwyr40oqdgoyw+wU9N66hkYTsc4UadIgASlJVMh2LXXsQtg==)
    bucket-name: mehado-java
  redis:
      host: localhost
      database: 0
      port: 6379
      password: ENC(wLMQPivDv4CWM6dbf9sAi+PMB/ujGSk390K9ZGv6GSwfhTwpOVLWoEC4P4CLE96c)
  rabbitmq:
    host: localhost
    port: 5672
    username: ENC(VSRwbwkCRPrz2dyrMRK9ynjiIjboG9aKBwXrNQAwWqJYFbyHHudvIqfs2LbUspoF)
    password: ENC(VSRwbwkCRPrz2dyrMRK9ynjiIjboG9aKBwXrNQAwWqJYFbyHHudvIqfs2LbUspoF)


  wechat:
    appid: wx0c9d3e46195ee4d8
    secret: ENC(0t1Tbv8VVsvoISIEFcuUbJHgA5oUMH5wnR+3jwcem3ggy//v7HForWzpxi3w/UKv3vBI9AyETA2CBrhPoMluzTRve55gzUrSvlOzf9cXLR8=)

  shop:
    address: 北京市海淀区上地信息路

  baidu:
    ak: your_baidu_ak